# Generated by Django 3.1.4 on 2020-12-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pp',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
