# Generated by Django 3.1.4 on 2020-12-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0002_category_pp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pp',
        ),
    ]
