# Generated by Django 3.1.4 on 2020-12-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0003_remove_category_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problemset.category'),
        ),
    ]
