# Generated by Django 3.1.4 on 2020-12-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0004_problem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
