# Generated by Django 3.1.4 on 2020-12-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0005_problem_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='hidden_test_cases',
            field=models.TextField(max_length=10000000, null=set),
            preserve_default=set,
        ),
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.TextField(max_length=1000, null=set),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case',
            field=models.TextField(max_length=10000, null=set),
        ),
    ]
