# Generated by Django 3.1.4 on 2020-12-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_auto_20201230_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Username', max_length=20, unique=set),
        ),
    ]
